{% set name = "affinegap" %}
{% set version = "1.12" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  # Use upstream archive tarball for tests
  url: https://github.com/dedupeio/affinegap/archive/refs/tags/v{{ version}}.tar.gz
  sha256: 2bf275b6d8b083bdb32b16fd4e4a55025eaad2ef6f325d3f0b0cdf8253608aaf

build:
  number: 2
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - cython
    - pip
    - python
    - setuptools
    - wheel
  run:
    - python

test:
  source_files:
    - tests
  imports:
    - affinegap
  requires:
    - pip
    - pytest
  commands:
    - pip check
    - pytest -v tests

about:
  home: https://github.com/dedupeio/affinegap
  summary: A Cython implementation of the affine gap string distance
  description: |
    A Cython implementation of the affine gap penalty string distance
    also known as the Smith–Waterman algorithm
  license: MIT
  license_file: LICENSE
  license_family: MIT
  doc_url: https://github.com/dedupeio/affinegap
  dev_url: https://github.com/dedupeio/affinegap

extra:
  recipe-maintainers:
    - osamples
    - izahn
